### ISSUE TITLE
Matching: UI for Invoice selection

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#130]
Invoice line items where field value PurchaseOrderId is not empty must be matched to corresponding matching candidate (PurchaseOrderItem or Goods Receipt Item).
Such invoices should be listed on page under Matching menu item.
![image](https://user-images.githubusercontent.com/24652264/30068158-8e1c1988-9265-11e7-9e30-22f153cf69e0.png)

**Comment by alevchuk-sc** [comment]
Done. Invoices that have at least one item with purchaseOrderId set are listed on matching page.

**Comment by pirttpi1** [comment]
If invoice has **invoice level po number**, the invoice should be shown under Matching (even though there's no po number on invoice line).

**Comment by alevchuk-sc** [comment]
Updated. Invoices are suitable for matching if they have invoice level po number.

**Comment by pirttpi1** [comment]
![image](https://user-images.githubusercontent.com/31001609/31116151-ae83cde6-a82d-11e7-8ea0-5ef385d6dcb1.png)
In matched lines (0/0) we should show the amount of invoice line items. So if there's three lines, but only one line item has PO number, we still show (0/3), because all the invoice lines should be matched, before invoice is matched.

**Comment by pirttpi1** [comment]
Ok.
